title = "Rayyan's Profile"
theme = "PaperMod"

# Default language settings
defaultContentLanguage = "en"
hasCJKLanguage = false

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1
    title = "Rayyan | Home"
    [languages.en.params]
      [languages.en.params.profileMode]
        enabled = true
        title = "Hi there! 👋"
        subtitle = "Welcome to my personal space. This is the English version of my profile site."
        imageUrl = "https://github.com/rayyangh.png"
        imageWidth = 150
        imageHeight = 150
        imageTitle = "Rayyan"
        [[languages.en.params.profileMode.buttons]]
          name = "Projects"
          url = "https://github.com/rayyangh/findme"
        [[languages.en.params.profileMode.buttons]]
          name = "GitHub"
          url = "https://github.com/rayyangh"
      [[languages.en.params.socialIcons]]
        name = "github"
        url = "https://github.com/rayyangh"

  [languages.ar]
    languageName = "العربية"
    languageCode = "ar"
    weight = 2
    title = "ريان | الرئيسية"
    [languages.ar.params]
      [languages.ar.params.profileMode]
        enabled = true
        title = "أهلاً بك! 👋"
        subtitle = "مرحباً بك في مساحتي الشخصية. هذه هي النسخة العربية لصفحتي التعريفية."
        imageUrl = "https://github.com/rayyangh.png"
        imageWidth = 150
        imageHeight = 150
        imageTitle = "ريان"
        [[languages.ar.params.profileMode.buttons]]
          name = "المشاريع"
          url = "https://github.com/rayyangh/findme"
        [[languages.ar.params.profileMode.buttons]]
          name = "غيت هاب"
          url = "https://github.com/rayyangh"
      [[languages.ar.params.socialIcons]]
        name = "github"
        url = "https://github.com/rayyangh"

# Global Parameters
[params]
  env = "production"
  showToC = false
  [params.Label]
    text = "FindMe"