title = "Rayyan's Profile"
theme = "PaperMod"

# Default language settings
defaultContentLanguage = "en"
hasCJKLanguage = false

[languages]
  [languages.en]
    languageName = "English"
    languageCode = "en-us"
    weight = 1
    title = "Rayyan | Home"
    [languages.en.params.profileMode]
      enabled = true
      title = "Hi there! 👋"
      subtitle = "Welcome. This is my profile site."
      imageUrl = "https://github.com/rayyangh.png"
      imageWidth = 150
      imageHeight = 150
      imageTitle = "Rayyan"
      [[languages.en.params.profileMode.buttons]]
        name = "Projects"
        url = "https://www.flickr.com/photos/201933183@N04/"

  [languages.ar]
    languageName = "العربية"
    languageCode = "ar"
    weight = 2
    title = "ريان | الرئيسية"
    [languages.ar.params.profileMode]
      enabled = true
      title = "أهلاً بك! 👋"
      subtitle = "مرحباً بك. هذه هي لصفحتي التعريفية."
      imageUrl = "https://github.com/rayyangh.png"
      imageWidth = 150
      imageHeight = 150
      imageTitle = "ريان"
      [[languages.ar.params.profileMode.buttons]]
        name = "المشاريع"
        url = "https://www.flickr.com/photos/201933183@N04/"

# Global Parameters (Applies to all languages automatically)
[params]
  env = "production"
  showToC = false
  displayFullLangName = true
  [params.Label]
    text = "FindMe"

  # Global Social Icons 
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/rayyangh"
  [[params.socialIcons]]
    name = "instagram"
    url = "https://instagram.com/rayyan.manzary"
  [[params.socialIcons]]
    name = "whatsapp"
    url = "https://wa.me/15202035786"
  [[params.socialIcons]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/rayyanmanzary/"
  [[params.socialIcons]]
    name = "flickr"
    url = "https://www.flickr.com/photos/201933183@N04/"
  [[params.socialIcons]]
    name = "snapchat"
    url = "https://snapchat.com/add/rayyan_manzary"
  [[params.socialIcons]]
    name = "telegram"
    url = "https://t.me/rayyantg"
  [[params.socialIcons]]
    name = "email"
    url = "mailto:rayyanbc@gmail.com"
